---

- name: OBS worker ohpc-lenovo-c3
  hosts: ohpc_lenovo_c3
  user: root
  gather_facts: true
  vars:
    obs_worker_instances: 30
    obs_worker_jobs: 6
    container_tag: amd64
    obs_repository_server: 10.255.254.0
    stunnel_remote_port: 8444
    openvpn_ifconfig: "10.255.254.1 10.255.254.0"

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: ../common/handlers.yml

  tasks:
    - name: Include history.yml
      ansible.builtin.include_tasks: ../common/history.yml

    - name: Include automatic-updates.yml
      ansible.builtin.include_tasks: ../common/automatic-updates.yml

    - name: Import ohpc-lenovo-common.yml
      ansible.builtin.import_tasks: ../test/ohpc-lenovo-common.yml

    - name: Create OBS directories
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - /workers/

    - name: Mount /workers partition
      ansible.posix.mount:
        path: /workers
        src: UUID=008f4b8a-66a7-40d1-957a-97cb19e3b582
        opts: defaults,noatime
        state: mounted
        fstype: xfs

    - name: Create OBS directories
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - /workers/cache
        - /etc/systemd/system/obsworker-podman.service.d
        - /etc/systemd/system/openvpn-client@obs.service.d

    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - epel-release

    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - podman
          - stunnel
          - openvpn
          - vim-enhanced
          - bash-completion
          - git

    - name: Install stunnel configuration
      ansible.builtin.template:
        src: stunnel.conf
        dest: /etc/stunnel/stunnel.conf
        owner: root
        group: root
        mode: "0600"

    - name: Install openvpn configuration
      ansible.builtin.template:
        src: openvpn-obs.conf
        dest: /etc/openvpn/client/obs.conf
        owner: root
        group: root
        mode: "0600"

    - name: Install openvpn override.conf
      ansible.builtin.copy:
        src: openvpn.service.override.conf
        dest: /etc/systemd/system/openvpn-client@obs.service.d/override.conf
        owner: root
        group: root
        mode: "0644"

    - name: Install obsworker override.conf
      ansible.builtin.copy:
        src: obsworker-podman.service.override.conf
        dest: /etc/systemd/system/obsworker-podman.service.d/override.conf
        owner: root
        group: root
        mode: "0644"

    - name: Include obs.yml
      ansible.builtin.include_tasks: ../common/obs.yml

    - name: Enable services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - stunnel
        - openvpn-client@obs
