FROM registry.opensuse.org/opensuse/leap:15.5

MAINTAINER The OpenHPC Project

COPY OBS_Server_2.10.repo /etc/zypp/repos.d/OBS_Server_2.10.repo

RUN zypper --no-gpg-checks -n install obs-worker hostname

COPY obs-server /etc/sysconfig/obs-server

ENTRYPOINT  ["/bin/bash", "-c", "/usr/sbin/obsworker start; sleep infinity"]
