---
name: Validate

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  lint_markdown:
    name: Run markdown linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            README.md

  lint:
    strategy:
      matrix:
        step: [codespell, shellcheck, whitespace, shfmt, ansible, ruff]
    name: Run ${{ matrix.step }} linter
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:
      - name: Setup
        run: dnf -y install codespell make python3-flake8 ShellCheck shfmt python3-ansible-lint ansible ruff
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.step }}
        run: make ${{ matrix.step }}-lint
